# Generated by Django 6.0.2 on 2026-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief summary for cards', max_length=300)),
                ('duration_days', models.IntegerField(help_text='Number of days')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('extreme', 'Extreme')], max_length=20)),
                ('max_altitude', models.IntegerField(help_text='Maximum altitude in meters')),
                ('best_season', models.CharField(help_text='e.g., March-May, September-November', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='treks/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this trek currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
