# Generated by Django 5.1.4 on 2026-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Starting point latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Starting point longitude', max_digits=9, null=True),
        ),
    ]
